#ifndef FLAG_H
#define FLAG_H

enum Flag {
    NEW_CLIENT_HELLO,
    CONFIRM_RECEPTION,
    HI,
    EXIT,
    FILE_INFO,
    REQUEST_FILE,
    HEADER_FILE,
    CONTENT_FILE,
    FINISH_FILE,
    REQUEST_ALL_PATH,
    RESPONSE_PATH,
    RESPONSE_PATH_FINISH,
    REQUEST_RESTORE,
    FILE_INFO_RESTORE,
    FILE_INFO_RESTORE_FINISH,
    REQUEST_FILE_RESTORE,
};

#endif
